name: Update Version Number

on:
  push:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-version-number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Version Number
        run: |
          OLD_VERSION=$(grep ^version pyproject.toml | cut -d '"' -f 2)
          echo 1 => ${OLD_VERSION}
          OLD_VERSION="\"$OLD_VERSION\""
          echo 2 => ${OLD_VERSION}
          NEW_VERSION="\"$GITHUB_REF_NAME\""
          echo 3 => ${NEW_VERSION}
          sed -i "s+version = $OLD_VERSION+version = $NEW_VERSION+g" pyproject.toml

      - name: Config user
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -a -m "Update version number to new_version"
          git push origin HEAD:add-end-to-end-test-after-package-upload
